# Generated by Django 3.2.16 on 2023-08-17 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '966453047'. Up to 10 digits allowed.", regex='^\\+?1?\\d{1,11}$')]),
        ),
    ]
