# Generated by Django 3.2.16 on 2023-08-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
